
fastlane_version "2.24.0"

default_platform :ios

platform :ios do
  before_all do
    # Before
  end

  desc "Screenshot demo"
  lane :demo do
    snapshot
  end

  after_all do |lane|
    # Success
  end

  error do |lane, exception|
    # Error
  end
end
