
fastlane_version "2.24.0"

default_platform :ios

platform :ios do
  before_all do
    # Before
  end

  desc "Version demo"
  lane :demo do
    ensure_git_status_clean
    increment_version_number
    increment_build_number
    commit_version_bump
  end

  after_all do |lane|
    # Success
  end

  error do |lane, exception|
    # Error
  end
end
